### ISSUE TITLE
warning says "not accepting talks yet" but it's actually after the deadline

### ISSUE THREAD

**Issue by dnordquist** [JudahGabriel/twincitiescodecamp#12]
I would expect, now that the talk submission deadline has passed, for there to be a different message saying "you're late", not "you're early". 

https://twincitiescodecamp.com/#/Events/22/talks

This could just be an admin thing - I might take a look later on - but I suspect this feature is just not implemented.

**Comment by JudahGabriel** [comment]
Hey Dan! Thanks for the bug report. Yeah, there's just a flag on the Event object: IsAcceptingTalkSubmissions or something like that. The UI should reflect that, rather than assuming you're too early. So really it's just a UI bug.

I'll fix this in the next update.

**Comment by JudahGabriel** [comment]
Fixed. Thanks for reporting the issue, and see you at Code Camp!
